---@diagnostic disable: undefined-global
local lush = require("lush")
local base = require("ivory_base")
local spec = lush(function()
	return {
		-- TELESCOPE/FZFLUA
		FzfLuaLivePrompt({ fg = "#574b42" }),
		TelescopeTitle({ bg = "#79241f", gui = "bold", fg = "#edeae4" }),
		TelescopePreviewTitle({ bg = "#352e2e", gui = "bold", fg = "#edeae4" }),
		TelescopePreviewNormal({ base.NormalFloat }),
		TelescopeResultsTitle({ bg = "#464c3a", gui = "bold", fg = "#e5e1d9" }),
		TelescopePromptTitle({ bg = "#79241f", gui = "bold", fg = "#e5e1d9" }),
		TelescopePromptPrefix({ gui = "bold", fg = "#7c4034" }),
		TelescopeResultsDiffUntracked({ TelescopePromptPrefix }),
		TelescopeMatching({ gui = "bold" }),
		TelescopePreviewBorder({ base.FloatBorder }),
		TelescopeResultsBorder({ bg = "#e5e1d9", fg = "#e5e1d9" }),
		TelescopePromptBorder({ bg = "#d7d3cb", fg = "#d7d3cb" }),
		TelescopePromptCounter({ bg = "#d7d3cb", fg = "#574b42" }),
		TelescopePromptNormal({ bg = "#d7d3cb" }),
		TelescopeBorder({ base.FloatBorder }),
		TelescopeNormal({ base.NormalFloat }),
		TelescopeMultiSelection({ gui = "bold", fg = "#352e2e" }),
		TelescopeSelectionCaret({ bg = "#d7d3cb", fg = "#352e2e" }),
		TelescopeSelection({ bg = "#e5e1d9", gui = "bold", fg = "#352e2e" }),
		TelescopeResultsConstant({}),
		TelescopeResultsClass({}),
		TelescopePreviewMessageFillchar({}),
		TelescopePreviewMessage({}),
		TelescopePreviewDate({}),
		TelescopePreviewGroup({}),
		TelescopePreviewUser({}),
		TelescopePreviewSize({}),
		TelescopePreviewSticky({}),
		TelescopePreviewHyphen({}),
		TelescopePreviewExecute({}),
		TelescopePreviewWrite({}),
		TelescopePreviewRead({}),
		TelescopePreviewSocket({}),
		TelescopePreviewLink({}),
		TelescopePreviewBlock({}),
		TelescopePreviewDirectory({}),
		TelescopePreviewCharDev({}),
		TelescopePreviewPipe({}),
		TelescopePreviewMatch({}),
		TelescopePreviewLine({}),
		TelescopeResultsNormal({}),
		TelescopeMultiIcon({}),
		TelescopeResultsDiffDelete({}),
		TelescopeResultsDiffAdd({}),
		TelescopeResultsDiffChange({}),
		TelescopeResultsNumber({}),
		TelescopeResultsIdentifier({}),
		TelescopeResultsLineNr({}),
		TelescopeResultsSpecialComment({}),
		TelescopeResultsVariable({}),
		TelescopeResultsComment({}),
		TelescopeResultsStruct({}),
		TelescopeResultsOperator({}),
		TelescopeResultsMethod({}),
		TelescopeResultsFunction({}),
		TelescopeResultsField({}),
		TelescopeBufferLoaded({}),
		TelescopePathSeparator({}),
		TelescopeFrecencyScores({}),
		TelescopeQueryFilter({}),
	}
end)
return spec
