local lush = require("lush")
local palette = require("palette")

---@diagnostic disable: undefined-global
-- selene: allow(undefined_variable)
-- stylua: ignore start
local spec = lush(function()
	return {
		-- NOICE
		NoiceCursor({ bg = palette.blue, fg = palette.infobg }),
		NoiceCmdline({ StatusLine }),
		NoiceVirtualText({ bg = palette.addbg, fg = palette.green }),
		NoicePopup({ Pmenu }),
		NoiceMini({ Pmenu }),
		NoiceCompletionItemKindFolder({}),
		NoiceCompletionItemKindDefault({}),
		NoiceCompletionItemKindText({}),
		NoiceCompletionItemKindEnumMember({}),
		NoiceCompletionItemKindUnit({}),
		NoiceCompletionItemKindField({}),
		NoiceCompletionItemKindFile({}),
		NoiceCompletionItemKindVariable({}),
		NoiceCompletionItemKindEnum({}),
		NoiceCompletionItemKindColor({}),
		NoiceCmdlinePopupBorderHelp({}),
		NoiceCmdlinePopupBorder({}),
		NoiceCmdlineIconCalculator({}),
		NoiceCmdlinePopupBorderCalculator({}),
		NoiceCmdlineIconLua({}),
		NoiceCmdlinePopupBorderLua({}),
		NoiceCmdlineIconInput({}),
		NoiceCmdlinePopupBorderInput({}),
		NoiceCmdlineIconHelp({}),
		NoiceCmdlinePopupBorderFilter({}),
		NoiceCmdlineIconCmdline({}),
		NoiceCmdlinePopupBorderCmdline({}),
		NoiceLspProgressClient({}),
		NoiceLspProgressSpinner({}),
		NoiceFormatLevelError({}),
		NoiceFormatLevelWarn({}),
		NoiceFormatLevelInfo({}),
		NoiceFormatLevelOff({}),
		NoiceFormatLevelTrace({}),
		NoiceFormatLevelDebug({}),
		NoiceFormatTitle({}),
		NoiceFormatConfirmDefault({}),
		NoiceFormatConfirm({}),
		NoiceFormatDate({}),
		NoiceFormatKind({}),
		NoiceFormatEvent({}),
		NoiceFormatProgressTodo({}),
		NoiceFormatProgressDone({ gui = "reverse" }),
		NoiceSplitBorder({}),
		NoiceSplit({}),
		NoiceCompletionItemKindKeyword({}),
		NoiceScrollbarThumb({}),
		NoiceCompletionItemKindModule({}),
		NoiceScrollbar({}),
		NoiceCompletionItemKindConstructor({}),
		NoicePopupmenuSelected({}),
		NoicePopupmenuMatch({}),
		NoicePopupmenuBorder({}),
		NoiceCompletionItemKindClass({}),
		NoicePopupmenu({}),
		NoicePopupBorder({}),
		NoiceCmdlineIconFilter({}),
		NoiceConfirmBorder({}),
		NoiceConfirm({}),
		NoiceCmdlinePopupBorderSearch({}),
		NoiceCmdlinePopupTitle({}),
		NoiceCmdlinePopup({}),
		NoiceCompletionItemKindMethod({}),
		NoiceCompletionItemKindFunction({}),
		NoiceCompletionItemKindInterface({}),
		NoiceCompletionItemKindStruct({}),
		NoiceLspProgressTitle({}),
		NoiceCompletionItemKindValue({}),
		NoiceCompletionItemKindProperty({}),
		NoiceCompletionItemKindConstant({}),
		NoiceCompletionItemKindSnippet({}),
		NoiceHiddenCursor({ blend = 100, gui = "nocombine" }),
	}
end)
return spec
