---@diagnostic disable: undefined-global
local lush = require("lush")
local base = require("ivory_base")
local spec = lush(function()
	return {
		-- TELESCOPE/FZFLUA
		TelescopeTitle({ bg = "#79241f", gui = "bold", fg = "#ded8d3" }),
		TelescopePreviewTitle({ bg = "#352e2e", gui = "bold", fg = "#ded8d3" }),
		TelescopePreviewNormal({ base.WinBar }),
		TelescopeResultsTitle({ bg = "#464c3a", gui = "bold", fg = "#c8beb7" }),
		TelescopePromptTitle({ bg = "#79241f", gui = "bold", fg = "#c8beb7" }),
		TelescopePromptPrefix({ gui = "bold", fg = "#7c4034" }),
		TelescopeResultsDiffUntracked({ TelescopePromptPrefix }),
		TelescopeMatching({ gui = "bold" }),
		TelescopePreviewBorder({ bg = "#ded8d3", fg = "#ded8d3" }),
		TelescopeResultsBorder({ bg = "#c8beb7", fg = "#c8beb7" }),
		TelescopePromptBorder({ bg = "#bdb1a8", fg = "#bdb1a8" }),
		TelescopePromptCounter({ bg = "#bdb1a8", fg = "#574b42" }),
		TelescopePromptNormal({ bg = "#bdb1a8" }),
		TelescopeBorder({ bg = "#c8beb7", fg = "#c8beb7" }),
		TelescopeNormal({ bg = "#c8beb7", fg = "#574b42" }),
		TelescopeMultiSelection({ gui = "bold", fg = "#352e2e" }),
		TelescopeSelectionCaret({ bg = "#bdb1a8", fg = "#352e2e" }),
		TelescopeSelection({ bg = "#bdb1a8", gui = "bold", fg = "#352e2e" }),
		TelescopeResultsConstant({}),
		TelescopeResultsClass({}),
		TelescopePreviewMessageFillchar({}),
		TelescopePreviewMessage({}),
		TelescopePreviewDate({}),
		TelescopePreviewGroup({}),
		TelescopePreviewUser({}),
		TelescopePreviewSize({}),
		TelescopePreviewSticky({}),
		TelescopePreviewHyphen({}),
		TelescopePreviewExecute({}),
		TelescopePreviewWrite({}),
		TelescopePreviewRead({}),
		TelescopePreviewSocket({}),
		TelescopePreviewLink({}),
		TelescopePreviewBlock({}),
		TelescopePreviewDirectory({}),
		TelescopePreviewCharDev({}),
		TelescopePreviewPipe({}),
		TelescopePreviewMatch({}),
		TelescopePreviewLine({}),
		TelescopeResultsNormal({}),
		TelescopeMultiIcon({}),
		TelescopeResultsDiffDelete({}),
		TelescopeResultsDiffAdd({}),
		TelescopeResultsDiffChange({}),
		TelescopeResultsNumber({}),
		TelescopeResultsIdentifier({}),
		TelescopeResultsLineNr({}),
		TelescopeResultsSpecialComment({}),
		TelescopeResultsVariable({}),
		TelescopeResultsComment({}),
		TelescopeResultsStruct({}),
		TelescopeResultsOperator({}),
		TelescopeResultsMethod({}),
		TelescopeResultsFunction({}),
		TelescopeResultsField({}),
		TelescopeBufferLoaded({}),
		TelescopePathSeparator({}),
		TelescopeFrecencyScores({}),
		TelescopeQueryFilter({}),
	}
end)
return spec
