local colors = {
	-- PATCH_OPEN
Normal = {fg = "#352e2e", bg = "#e9e5e2"},
Boolean = {fg = "#543227"},
["@boolean"] = {link = "Boolean"},
Character = {fg = "#493f37"},
SpecialKey = {link = "Character"},
["@character"] = {link = "Character"},
["@string.escape"] = {link = "Character"},
ColorColumn = {bg = "#ded8d3"},
debugPC = {link = "ColorColumn"},
Comment = {fg = "#837163"},
["@comment"] = {link = "Comment"},
["@lsp.type.comment"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
["@org.agenda.deadline"] = {link = "Conceal"},
["@punctuation.bracket"] = {link = "Conceal"},
Conditional = {fg = "#543227", italic = true},
PreCondit = {link = "Conditional"},
Typedef = {link = "Conditional"},
["@conditional"] = {link = "Conditional"},
["@constant.builtin"] = {link = "Conditional"},
Constant = {fg = "#545468"},
["@constant"] = {link = "Constant"},
["@lsp.type.enumMember"] = {link = "Constant"},
CurSearch = {bg = "#ced3dd"},
CursorColumn = {bg = "#493f37"},
CursorLine = {bg = "#ded8d3"},
CursorLineNr = {fg = "#493f37"},
Define = {fg = "#493f37", bold = true},
["@constant.macro"] = {link = "Define"},
["@define"] = {link = "Define"},
["@type.definition"] = {link = "Define"},
Delimiter = {fg = "#9e8d7f"},
Conceal = {link = "Delimiter"},
Noise = {link = "Delimiter"},
["@markup.heading.1.marker"] = {link = "Delimiter"},
["@markup.heading.2.marker"] = {link = "Delimiter"},
["@markup.heading.3.marker"] = {link = "Delimiter"},
["@markup.heading.4.marker"] = {link = "Delimiter"},
["@markup.heading.5.marker"] = {link = "Delimiter"},
["@markup.heading.6.marker"] = {link = "Delimiter"},
["@punctuation"] = {link = "Delimiter"},
DiagnosticFloatingOk = {fg = "#464c3a"},
DiagnosticSignOk = {link = "DiagnosticFloatingOk"},
LspDiagnosticsSignError = {link = "DiagnosticSignError"},
LspDiagnosticsSignHint = {link = "DiagnosticSignHint"},
LspDiagnosticsSignInformation = {link = "DiagnosticSignInfo"},
LspDiagnosticsSignWarning = {link = "DiagnosticSignWarn"},
DiagnosticUnderlineOk = {sp = "#464c3a", undercurl = true},
DiagnosticUnnecessary = {sp = "#574b42", underdotted = true},
DiffAdd = {fg = "#637337", bg = "#dae5cd"},
DiagnosticOk = {link = "DiffAdd"},
diffAdded = {link = "DiffAdd"},
DiffChange = {fg = "#735057", bg = "#e1d2d6"},
DiffDelete = {fg = "#834c40", bg = "#ecd5d3"},
Todo = {link = "DiffDelete"},
diffRemoved = {link = "DiffDelete"},
DiffFGAdd = {fg = "#637337"},
DiffFGChange = {fg = "#735057"},
DiffFGDelete = {fg = "#834c40"},
DiffFGText = {fg = "#493f37"},
DiffText = {fg = "#493f37", bg = "#c8beb7"},
Directory = {fg = "#545468", bold = true},
["@namespace"] = {link = "Directory"},
["@org.agenda.scheduled"] = {link = "Directory"},
Error = {fg = "#79241f", bg = "#dcb2a7"},
DiagnosticError = {link = "Error"},
DiagnosticSignError = {link = "Error"},
["@text.danger"] = {link = "Error"},
ErrorMsg = {fg = "#79241f"},
DiagnosticFloatingError = {link = "ErrorMsg"},
debugBreakpoint = {link = "ErrorMsg"},
["@function.macro"] = {link = "ErrorMsg"},
Exception = {fg = "#735057", bold = true},
FloatBorder = {fg = "#c8beb7", bg = "#c8beb7"},
FloatShadow = {bg = "black", blend = 80},
FloatShadowThrough = {bg = "black", blend = 100},
FoldColumn = {fg = "#9e8d7f", bg = "#e9e5e2", bold = true},
CursorLineFold = {link = "FoldColumn"},
Folded = {fg = "#9e8d7f", bg = "#ded8d3"},
Function = {fg = "#352e2e", bold = true},
["@function"] = {link = "Function"},
["@lsp.type.decorator"] = {link = "Function"},
["@lsp.type.function"] = {link = "Function"},
["@lsp.type.method"] = {link = "Function"},
["@method"] = {link = "Function"},
Hint = {fg = "#735057", bg = "#dbc4c8"},
DiagnosticHint = {link = "Hint"},
DiagnosticSignHint = {link = "Hint"},
HintMsg = {fg = "#735057"},
DiagnosticFloatingHint = {link = "HintMsg"},
Identifier = {fg = "#352e2e"},
["@lsp.type.parameter"] = {link = "Identifier"},
["@lsp.type.property"] = {link = "Identifier"},
["@lsp.type.variable"] = {link = "Identifier"},
["@punctuation.delimiter"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
IncSearch = {reverse = true},
Cursor = {link = "IncSearch"},
MatchParen = {link = "IncSearch"},
Include = {fg = "#735057", italic = true},
["@include"] = {link = "Include"},
Info = {fg = "#545468", bg = "#ced3dd"},
DiagnosticInfo = {link = "Info"},
DiagnosticSignInfo = {link = "Info"},
["@text.note"] = {link = "Info"},
InfoMsg = {fg = "#545468"},
DiagnosticFloatingInfo = {link = "InfoMsg"},
Keyword = {fg = "#735057"},
Label = {fg = "#735057", bold = true},
LineNr = {fg = "#bdb1a8"},
LspInfoBorder = {},
LspInfoFiletype = {},
LspInfoList = {},
LspInfoTip = {},
LspInfoTitle = {},
LspInlayHint = {fg = "#837163", bg = "#ded8d3"},
Macro = {fg = "#545468", italic = true},
["@lsp.type.macro"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
MoreMsg = {fg = "#837163"},
NonText = {fg = "#c8beb7"},
EndOfBuffer = {link = "NonText"},
Ignore = {link = "NonText"},
Whitespace = {link = "NonText"},
NormalFloat = {fg = "#493f37", bg = "#c8beb7"},
Number = {fg = "#735057"},
Float = {link = "Number"},
Type = {link = "Number"},
["@number"] = {link = "Number"},
Operator = {fg = "#837163"},
Pmenu = {fg = "#493f37", bg = "#c8beb7"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {fg = "#bdb1a8", bg = "#c8beb7"},
PmenuSel = {fg = "#493f37", bg = "#bdb1a8", bold = true},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
WildMenu = {link = "PmenuSel"},
PmenuThumb = {fg = "#837163", bg = "#837163"},
PreProc = {fg = "#573e1a"},
["@preproc"] = {link = "PreProc"},
Question = {fg = "#573e1a"},
["@property"] = {link = "Question"},
QuickFixLine = {bg = "#9e8d7f"},
RedrawDebugClear = {bg = "yellow"},
RedrawDebugComposed = {bg = "green"},
RedrawDebugNormal = {reverse = true},
RedrawDebugRecompose = {bg = "red"},
Repeat = {fg = "#543227"},
SpecialChar = {link = "Repeat"},
["@keyword"] = {link = "Repeat"},
["@keyword.function"] = {link = "Repeat"},
["@keyword.return"] = {link = "Repeat"},
["@repeat"] = {link = "Repeat"},
["@variable.builtin"] = {link = "Repeat"},
Search = {reverse = true},
Substitute = {link = "Search"},
SignColumn = {},
Special = {fg = "#79241f", bold = true},
["@lsp.type.keyword.yaml.ansible"] = {link = "Special"},
SpecialComment = {fg = "#574b42", bold = true},
["@lsp.type.keyword.lua"] = {link = "SpecialComment"},
SpellBad = {sp = "#79241f", undercurl = true},
DiagnosticUnderlineError = {link = "SpellBad"},
SpellCap = {sp = "#735057", undercurl = true},
DiagnosticUnderlineHint = {link = "SpellCap"},
SpellLocal = {sp = "#543227", undercurl = true},
DiagnosticUnderlineWarn = {link = "SpellLocal"},
SpellRare = {sp = "#545468", undercurl = true},
DiagnosticUnderlineInfo = {link = "SpellRare"},
Statement = {fg = "#543227"},
StatusLine = {fg = "#352e2e", bg = "#ded8d3"},
MsgArea = {link = "StatusLine"},
MsgSeparator = {link = "StatusLine"},
StatusLineTerm = {link = "StatusLine"},
StatusLineNC = {fg = "#574b42", bg = "#ded8d3"},
StatusLineTermNC = {link = "StatusLineNC"},
StorageClass = {fg = "#543227", bold = true},
Structure = {link = "StorageClass"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#493f37", italic = true},
["@markup.literal"] = {link = "String"},
["@string"] = {link = "String"},
TSPlaygroundFocus = {},
TSPlaygroundLang = {},
TSQueryLinterError = {},
TabLine = {fg = "#746458", bg = "#bdb1a8"},
TabLineFill = {bg = "#bdb1a8"},
TabLineSel = {fg = "#574b42", bg = "#ded8d3"},
TermCursor = {reverse = true},
Title = {bold = true},
FloatTitle = {link = "Title"},
["@text.title"] = {link = "Title"},
Underlined = {fg = "#573e1a", sp = "#573e1a", underline = true},
Tag = {link = "Underlined"},
["@text.underline"] = {link = "Underlined"},
["@text.uri"] = {link = "Underlined"},
VertSplit = {fg = "#ded8d3", bg = "#e9e5e2"},
WinSeparator = {link = "VertSplit"},
Visual = {bg = "#c8beb7"},
VisualNOS = {link = "Visual"},
Warning = {fg = "#573e1a", bg = "#d6c890"},
DiagnosticSignWarn = {link = "Warning"},
DiagnosticWarn = {link = "Warning"},
["@text.warning"] = {link = "Warning"},
WarningMsg = {fg = "#573e1a"},
Debug = {link = "WarningMsg"},
DiagnosticFloatingWarn = {link = "WarningMsg"},
ModeMsg = {link = "WarningMsg"},
WinBar = {bg = "#ded8d3"},
WinBarNC = {link = "WinBar"},
lCursor = {fg = "bg", bg = "fg"},
["@error"] = {fg = "#7c4034", sp = "#7c4034", undercurl = true},
["@exception"] = {fg = "#8e3d63", italic = true},
["@field"] = {fg = "#493f37"},
["@function.builtin"] = {fg = "#545468", bold = true},
["@label"] = {fg = "#545468"},
["@markup.heading"] = {fg = "#7c4034", sp = "#7c4034", bold = true, underline = true},
["@markup.heading.1"] = {fg = "#735057", bg = "#dbc4c8", bold = true},
["@markup.heading.2"] = {fg = "#545468", bg = "#ced3dd", bold = true},
["@markup.heading.3"] = {fg = "#573e1a", bg = "#d6c890", bold = true},
["@markup.heading.4"] = {fg = "#735057", bg = "#deb9b9", bold = true},
["@markup.heading.5"] = {fg = "#545468", bg = "#ced3dd", bold = true},
["@markup.heading.6"] = {fg = "#673d58", bg = "#d1bed0", bold = true},
["@markup.italic"] = {italic = true},
["@markup.link.label"] = {fg = "#545468"},
["@markup.link.url"] = {fg = "#464c3a", underline = true},
["@markup.quote"] = {fg = "#574b42", italic = true},
["@markup.raw"] = {fg = "#493f37", bg = "#ded8d3"},
["@markup.raw.block"] = {},
["@markup.strikethrough"] = {fg = "#493f37", strikethrough = true},
["@markup.strong"] = {bold = true},
["@org.headline.level1"] = {fg = "#352e2e", bold = true},
["@org.headline.level2"] = {fg = "#545468", bold = true},
["@org.headline.level3"] = {fg = "#735057", bold = true},
["@org.headline.level4"] = {fg = "#464c3a", bold = true},
["@org.headline.level5"] = {fg = "#543227", bold = true},
["@org.headline.level6"] = {fg = "#573e1a", bold = true},
["@org.keyword.done"] = {fg = "#464c3a", bg = "#d0d8cc"},
["@org.keyword.todo"] = {fg = "#735057", bg = "#dbc4c8"},
["@parameter"] = {fg = "#543227"},
["@punctuation.special"] = {fg = "#746458", bold = true},
["@string.special.url"] = {fg = "#464c3a", underline = true},
["@text.reference"] = {fg = "#735057"},
["@text.strike"] = {fg = "#493f37", strikethrough = true},
	-- PATCH_CLOSE
}

vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.o.termguicolors = true
vim.o.background = "light"
vim.g.colors_name = "ivory"

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
